baseURL = 'https://anthology4tech.com/'
locale = 'en-us'
title = 'Anthology4Tech'
theme = "blowfish-2"

[markup.goldmark.renderer]
unsafe = true

###mainSections = ["posts"]
###mainSections = ["posts", "it", "environment", "os", "ai", "devops", "cloud", "security", "iac", "containers", "tools-apps", "tutorials"]
mainSections = ["posts", "it"]


[params]
  toc = true
  tocOpen = true

  showReadingTime = true
  showDate = true
  showAuthor = true
  showTags = true
  showCategories = true
  showSeries = true

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

#🟦 Column 1 — Top‑Level Menus

[menu]

  [[menu.main]]
    name = "Anthology Atelier"
    url = "https://anthologyatelier.com/"
    weight = 1
    identifier = "anthologyatelier"

  [[menu.main]]
    name = "IT - Info. Tech."
    url = "/it/"
    weight = 2
    identifier = "it"

  [[menu.main]]
    name = "ALM Mag"
    pageRef = "alm-mag"
    identifier = "alm-mag"
    weight = 3 

 [[menu.main]]
    name = "Improvement"
    url = "/improvement/"
    weight = 4
    identifier = "improvement"

  [[menu.main]]
    name = "Posts / Blog"
    url = "/posts/"
    weight = 5
    identifier = "posts"

  [[menu.main]]
    name = "About"
    url = "/About/"
    weight = 6
    identifier = "about"

#🟦 Column 2 — Dropdowns Under IT - Info. Tech.

  [[menu.main]]
    name = "Environment"
    url = "/it/environment/"
    parent = "it"
    weight = 1
    identifier = "environment"

  [[menu.main]]
    name = "OS"
    url = "/it/os/"
    parent = "it"
    weight = 2
    identifier = "os"

  [[menu.main]]
    name = "AI"
    url = "/it/ai/"
    parent = "it"
    weight = 3
    identifier = "ai"

  [[menu.main]]
    name = "DevOps / ALM"
    url = "/it/devops/"
    parent = "it"
    weight = 4
    identifier = "devops"

  [[menu.main]]
    name = "Cloud"
    url = "/it/cloud/"
    parent = "it"
    weight = 5
    identifier = "cloud"

  [[menu.main]]
    name = "Security"
    url = "/it/security/"
    parent = "it"
    weight = 6
    identifier = "security"

  [[menu.main]]
    name = "IaC"
    url = "/it/iac/"
    parent = "it"
    weight = 7
    identifier = "iac"

  [[menu.main]]
    name = "Containers"
    url = "/it/containers/"
    parent = "it"
    weight = 8
    identifier = "containers"

  [[menu.main]]
    name = "Tools & Apps"
    url = "/it/tools-apps/"
    parent = "it"
    weight = 9
    identifier = "tools-apps"
	
  [[menu.main]]
    name = "Tutorials"
    url = "/it/tutorials/"
    parent = "it"
    weight = 10
    identifier = "tutorials"

#🟦 Column 2 — Dropdowns Under ALM Mag

  [[menu.main]]
    name = "Issue 1"
    pageRef = "alm-mag/issue-1"
    parent = "alm-mag"
    weight = 1
    identifier = "issue1"  

  [[menu.main]]
    name = "Issue 2"
    pageRef = "alm-mag/issue-2"
    parent = "alm-mag"
    weight = 2
    identifier = "issue-2"

  [[menu.main]]
    name = "Issue 3"
    pageRef = "alm-mag/issue-3"
    parent = "alm-mag"
    weight = 3
    identifier = "issue-3"

  [[menu.main]]
    name = "Issue 4"
    pageRef = "alm-mag/issue-4"
    parent = "alm-mag"
    weight = 4
    identifier = "issue-4"

  [[menu.main]]
    name = "Issue 5 - Currently Under Construction"
    url = "#"
    pageRef = "alm-mag/issue-5"
    parent = "alm-mag"
    weight = 5
    identifier = "issue-5"

#🟦 Column 2 — Dropdowns Under Improvement

  [[menu.main]]
    name = "Personal Improvement"
    url = "/improvement/personal/"
    parent = "improvement"
    weight = 1
    identifier = "personal"

  [[menu.main]]
    name = "Resume"
    url = "/improvement/resume/"
    parent = "improvement"
    weight = 2
    identifier = "resume"

  [[menu.main]]
    name = "LinkedIn"
    url = "/improvement/linkedin/"
    parent = "improvement"
    weight = 3
    identifier = "linkedin"

  [[menu.main]]
    name = "Managerial"
    url = "/improvement/managerial/"
    parent = "improvement"
    weight = 4
    identifier = "managerial"

#🟦 Column 2 — Dropdowns Under Posts/Blogs

#🟦 Column 2 — Dropdowns About

#🟦 Column 3 — Deep Dropdowns Under Environment

  [[menu.main]]
    name = "Platform"
    url = "/it/environment/Platform/"
    parent = "environment"
    weight = 1

  [[menu.main]]
    name = "Networks/VMs"
    url = "/it/environment/networks/"
    parent = "environment"
    weight = 2

  [[menu.main]]
    name = "GitHub"
    url = "/it/environment/github/"
    parent = "environment"
    weight = 3

  [[menu.main]]
    name = "Cloudflare Pages"
    url = "/it/environment/cloudflare/"
    parent = "environment"
    weight = 4

#🟦 Column 3 — Deep Dropdowns Under OS

  [[menu.main]]
    name = "Windows"
    url = "/it/os/windows/"
    parent = "os"
    weight = 1

  [[menu.main]]
    name = "Mac"
    url = "/it/os/mac/"
    parent = "os"
    weight = 2

  [[menu.main]]
    name = "Linux"
    url = "/it/os/linux/"
    parent = "os"
    weight = 3

#🟦 Column 3 — Deep Dropdowns Under AI

  [[menu.main]]
    name = "ChatBots"
    url = "/it/ai/chatbots/"
    parent = "ai"
    weight = 1

  [[menu.main]]
    name = "Agents"
    url = "/it/ai/agents/"
    parent = "ai"
    weight = 2

  [[menu.main]]
    name = "LLMs"
    url = "/it/ai/llms/"
    parent = "ai"
    weight = 3

#🟦 Column 3 — Deep Dropdowns Under DevOps

  [[menu.main]]
    name = "CI/CD"
    url = "/it/devops/cicd/"
    parent = "devops"
    weight = 1

  [[menu.main]]
    name = "GitOps"
    url = "/it/devops/gitops/"
    parent = "devops"
    weight = 2

  [[menu.main]]
    name = "Infrastructure as Code"
    url = "/it/devops/iac/"
    parent = "devops"
    weight = 3

#🟦 Column 3 — Deep Dropdowns Under Cloud

  [[menu.main]]
    name = "Azure"
    url = "/it/cloud/azure/"
    parent = "cloud"
    weight = 1

  [[menu.main]]
    name = "AWS"
    url = "/it/cloud/aws/"
    parent = "cloud"
    weight = 2

  [[menu.main]]
    name = "GCP"
    url = "/it/cloud/gcp/"
    parent = "cloud"
    weight = 3

  [[menu.main]]
    name = "Oracle"
    url = "/it/cloud/oracle/"
    parent = "cloud"
    weight = 4

#🟦 Column 3 — Deep Dropdowns Under Security

  [[menu.main]]
    name = "Code"
    url = "/it/security/code/"
    parent = "security"
    weight = 1

  [[menu.main]]
    name = "Platform"
    url = "/it/security/platform/"
    parent = "security"
    weight = 2

  [[menu.main]]
    name = "AI"
    url = "/it/security/ai/"
    parent = "security"
    weight = 3

#🟦 Column 3 — Deep Dropdowns Under IaC

  [[menu.main]]
    name = "Terraform"
    url = "/it/iac/terraform/"
    parent = "iac"
    weight = 1

  [[menu.main]]
    name = "ARM"
    url = "/it/iac/arm/"
    parent = "iac"
    weight = 2

  [[menu.main]]
    name = "Bicep"
    url = "/it/iac/bicep/"
    parent = "iac"
    weight = 3

#🟦 Column 3 — Deep Dropdowns Under Containers

  [[menu.main]]
    name = "Docker"
    url = "/it/containers/docker/"
    parent = "containers"
    weight = 1

  [[menu.main]]
    name = "Kubernetes"
    url = "/it/containers/kubernetes/"
    parent = "containers"
    weight = 2

#🟦 Column 3 — Deep Dropdowns Under Tools & Apps

  [[menu.main]]
    name = "HUGO"
    url = "/it/tools-apps/hugo/"
    parent = "tools-apps"
    weight = 1

  [[menu.main]]
    name = "TiddlyWiki"
    url = "/it/tools-apps/tiddlywiki/"
    parent = "tools-apps"
    weight = 2

  [[menu.main]]
    name = "[potentially many]"
    url = "/it/tools-apps/many/"
    parent = "tools-apps"
    weight = 3

#🟦 Column 3 — Deep Dropdowns Under Tutorials

  [[menu.main]]
    name = "[potentially many]"
    url = "/it/tutorials/many/"
    parent = "tutorials"
    weight = 1
	
#🟦 Column 3 — Deep Dropdowns Under Personal

#🟦 Column 3 — Deep Dropdowns Under Resume

#🟦 Column 3 — Deep Dropdowns Under LinkedIn

#🟦 Column 3 — Deep Dropdowns Under Managerial

#🟦 Column 3 — Deep Dropdowns Under Opinion/research
