baseURL = 'https://anthology4tech.com/'
locale = 'en-us'
title = 'Anthology4Tech'
theme = "blowfish"

mainSections = ["posts"]

[params]
  toc = true
  tocOpen = true

  showReadingTime = true
  showDate = true
  showAuthor = true
  showTags = true
  showCategories = true
  showSeries = true

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

#🟦 Column 1 — Top‑Level Menus

[menu]

  [[menu.main]]
    name = "Anthology Atelier"
    url = "https://anthologyatelier.com/"
    weight = 1
    identifier = "anthologyatelier"

  [[menu.main]]
    name = "IT / Topics"
    url = "/topics/"
    weight = 2
    identifier = "topics"

  [[menu.main]]
    name = "ALM Mag"
    pageRef = "alm-mag"
    identifier = "alm-mag"
    weight = 3 

 [[menu.main]]
    name = "Personal Improvement"
    url = "/personal-improvement/"
    weight = 4
    identifier = "personal-improvement"

  [[menu.main]]
    name = "Posts / Blog"
    url = "/posts/"
    weight = 5
    identifier = "posts"

  [[menu.main]]
    name = "About"
    url = "/About/"
    weight = 6
    identifier = "about"

#🟦 Column 2 — Dropdowns Under Topics

  [[menu.main]]
    name = "Environment"
    url = "/topics/environment/"
    parent = "topics"
    weight = 1
    identifier = "environment"

  [[menu.main]]
    name = "OS"
    url = "/topics/os/"
    parent = "topics"
    weight = 2
    identifier = "os"

  [[menu.main]]
    name = "AI"
    url = "/topics/ai/"
    parent = "topics"
    weight = 3
    identifier = "ai"

  [[menu.main]]
    name = "DevOps / ALM"
    url = "/topics/devops/"
    parent = "topics"
    weight = 4
    identifier = "devops"

  [[menu.main]]
    name = "Cloud"
    url = "/topics/cloud/"
    parent = "topics"
    weight = 5
    identifier = "cloud"

  [[menu.main]]
    name = "Security"
    url = "/topics/security/"
    parent = "topics"
    weight = 6
    identifier = "security"

  [[menu.main]]
    name = "IaC"
    url = "/topics/iac/"
    parent = "topics"
    weight = 7
    identifier = "iac"

  [[menu.main]]
    name = "Containers"
    url = "/topics/containers/"
    parent = "topics"
    weight = 8
    identifier = "containers"

  [[menu.main]]
    name = "Tutorials"
    url = "/topics/tutorials/"
    parent = "topics"
    weight = 9
    identifier = "tutorials"

  [[menu.main]]
    name = "3rd Party Tools/Apps"
    url = "/topics/3rdparty/"
    parent = "topics"
    weight = 10
    identifier = "3rdparty"

#🟦 Column 2 — Dropdowns Under ALM Mag

  [[menu.main]]
    name = "Issue 1"
    pageRef = "alm-mag/issue-1"
    parent = "alm-mag"
    weight = 1
    identifier = "issue1"  

  [[menu.main]]
    name = "Issue 2"
    pageRef = "alm-mag/issue-2"
    parent = "alm-mag"
    weight = 2
    identifier = "issue-2"

  [[menu.main]]
    name = "Issue 3"
    pageRef = "alm-mag/issue-3"
    parent = "alm-mag"
    weight = 3
    identifier = "issue-3"

  [[menu.main]]
    name = "Issue 4"
    pageRef = "alm-mag/issue-4"
    parent = "alm-mag"
    weight = 4
    identifier = "issue-4"

  [[menu.main]]
    name = "Issue 5 - Currently Under Construction"
    url = "#"
    pageRef = "alm-mag/issue-5"
    parent = "alm-mag"
    weight = 5
    identifier = "issue-5"

#🟦 Column 2 — Dropdowns Under Personal Improvement

  [[menu.main]]
    name = "Managerial"
    url = "/personal-improvement/managerial/"
    parent = "personal-improvement"
    weight = 1
    identifier = "managerial"

  [[menu.main]]
    name = "Resume/LinkedIn"
    url = "/personal-improvement/resumeli/"
    parent = "personal-improvement"
    weight = 2
    identifier = "resumeli"

#🟦 Column 2 — Dropdowns Under Posts/Blogs

#🟦 Column 2 — Dropdowns About

#🟦 Column 3 — Deep Dropdowns Under Environment

  [[menu.main]]
    name = "Platform"
    url = "/topics/environment/Platform/"
    parent = "environment"
    weight = 1

  [[menu.main]]
    name = "Networks/VMs"
    url = "/topics/environment/networks/"
    parent = "environment"
    weight = 2

  [[menu.main]]
    name = "GitHub"
    url = "/topics/environment/github/"
    parent = "environment"
    weight = 3

  [[menu.main]]
    name = "Cloudflare Pages"
    url = "/topics/environment/cloudflare/"
    parent = "environment"
    weight = 4

#🟦 Column 3 — Deep Dropdowns Under OS

  [[menu.main]]
    name = "Windows"
    url = "/topics/os/windows/"
    parent = "os"
    weight = 1

  [[menu.main]]
    name = "Mac"
    url = "/topics/os/mac/"
    parent = "os"
    weight = 2

  [[menu.main]]
    name = "Linux"
    url = "/topics/os/linux/"
    parent = "os"
    weight = 3

#🟦 Column 3 — Deep Dropdowns Under AI

  [[menu.main]]
    name = "ChatBots"
    url = "/topics/ai/chatbots/"
    parent = "ai"
    weight = 1

  [[menu.main]]
    name = "Agents"
    url = "/topics/ai/agents/"
    parent = "ai"
    weight = 2

  [[menu.main]]
    name = "LLMs"
    url = "/topics/ai/llms/"
    parent = "ai"
    weight = 3

#🟦 Column 3 — Deep Dropdowns Under DevOps

  [[menu.main]]
    name = "CI/CD"
    url = "/topics/devops/cicd/"
    parent = "devops"
    weight = 1

  [[menu.main]]
    name = "GitOps"
    url = "/topics/devops/gitops/"
    parent = "devops"
    weight = 2

  [[menu.main]]
    name = "Infrastructure as Code"
    url = "/topics/devops/iac/"
    parent = "devops"
    weight = 3

#🟦 Column 3 — Deep Dropdowns Under Cloud

  [[menu.main]]
    name = "Azure"
    url = "/topics/cloud/azure/"
    parent = "cloud"
    weight = 1

  [[menu.main]]
    name = "AWS"
    url = "/topics/cloud/aws/"
    parent = "cloud"
    weight = 2

  [[menu.main]]
    name = "GCP"
    url = "/topics/cloud/gcp/"
    parent = "cloud"
    weight = 3

  [[menu.main]]
    name = "Oracle"
    url = "/topics/cloud/oracle/"
    parent = "cloud"
    weight = 4

#🟦 Column 3 — Deep Dropdowns Under Security

  [[menu.main]]
    name = "Code"
    url = "/topics/security/code/"
    parent = "security"
    weight = 1

  [[menu.main]]
    name = "Platform"
    url = "/topics/security/platform/"
    parent = "security"
    weight = 2

  [[menu.main]]
    name = "AI"
    url = "/topics/security/ai/"
    parent = "security"
    weight = 3

#🟦 Column 3 — Deep Dropdowns Under IaC

  [[menu.main]]
    name = "Terraform"
    url = "/topics/iac/terraform/"
    parent = "iac"
    weight = 1

  [[menu.main]]
    name = "ARM"
    url = "/topics/iac/arm/"
    parent = "iac"
    weight = 2

  [[menu.main]]
    name = "Bicep"
    url = "/topics/iac/bicep/"
    parent = "iac"
    weight = 3

#🟦 Column 3 — Deep Dropdowns Under Containers

  [[menu.main]]
    name = "Docker"
    url = "/topics/containers/docker/"
    parent = "containers"
    weight = 1

  [[menu.main]]
    name = "Kubernetes"
    url = "/topics/containers/kubernetes/"
    parent = "containers"
    weight = 2

#🟦 Column 3 — Deep Dropdowns Under Tutorials

  [[menu.main]]
    name = "[potentially many]"
    url = "/topics/tutorials/many/"
    parent = "tutorials"
    weight = 1

#🟦 Column 3 — Deep Dropdowns Under 3rdparty

  [[menu.main]]
    name = "HUGO"
    url = "/topics/3rdparty/hugo/"
    parent = "3rdparty"
    weight = 1

  [[menu.main]]
    name = "TiddlyWiki"
    url = "/topics/3rdparty/tiddlywiki/"
    parent = "3rdparty"
    weight = 2

  [[menu.main]]
    name = "[potentially many]"
    url = "/topics/3rdparty/many/"
    parent = "3rdparty"
    weight = 3

#🟦 Column 3 — Deep Dropdowns Under Managerial

#🟦 Column 3 — Deep Dropdowns Under Resume/LinkedIn

#🟦 Column 3 — Deep Dropdowns Under Opinion/research
